from flask import Flask, render_template, request, redirect, url_for, session, send_file
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors
from io import BytesIO

app = Flask(__name__)
app.secret_key = "cgpa_calculator_secret"


# =========================
# LOGIN
# =========================

@app.route("/")
def login():
    return render_template("login.html")


@app.route("/login", methods=["POST"])
def login_user():

    student_name = request.form["student_name"]
    reg_no = request.form["reg_no"]

    session["student_name"] = student_name
    session["reg_no"] = reg_no

    return redirect(url_for("dashboard"))


# =========================
# DASHBOARD
# =========================

@app.route("/dashboard")
def dashboard():

    student_name = session.get("student_name", "Student")
    reg_no = session.get("reg_no", "N/A")

    return render_template(
        "dashboard.html",
        student_name=student_name,
        reg_no=reg_no
    )


# =========================
# GPA PAGE
# =========================

@app.route("/gpa")
def gpa():
    return render_template("gpa.html")


# =========================
# CGPA PAGE
# =========================

@app.route("/cgpa")
def cgpa():

    semester_data = session.get("semester_data", {})

    return render_template(
        "cgpa.html",
        semester_data=semester_data
    )


# =========================
# SAVE GPA
# =========================

@app.route("/save-gpa", methods=["POST"])
def save_gpa():

    data = request.get_json()

    semester = data["semester"]
    gpa = data["gpa"]
    credits = data["credits"]
    subjects = data["subjects"]

    # Save semester GPA + credits for CGPA
    if "semester_data" not in session:
        session["semester_data"] = {}

    semester_data = session["semester_data"]

    semester_data[f"Sem {semester}"] = {
        "gpa": gpa,
        "credits": credits
    }

    session["semester_data"] = semester_data

    # Save detailed GPA report for PDF
    session["gpa_report"] = {
        "semester": semester,
        "gpa": gpa,
        "credits": credits,
        "subjects": subjects
    }

    return {
        "message": "GPA data saved successfully"
    }

# =========================
# SAVE CGPA
# =========================

@app.route("/save-cgpa", methods=["POST"])
def save_cgpa():

    data = request.get_json()

    cgpa = data["cgpa"]

    session["cgpa"] = cgpa

    return {
        "message": "CGPA saved successfully"
    }


# =========================
# DOWNLOAD CGPA PDF
# =========================

@app.route("/download-cgpa-pdf")
def download_cgpa_pdf():

    student_name = session.get("student_name", "Student")
    reg_no = session.get("reg_no", "N/A")
    cgpa = session.get("cgpa", "N/A")
    semester_data = session.get("semester_data", {})

    pdf_buffer = BytesIO()

    pdf = canvas.Canvas(pdf_buffer)

    pdf.setTitle("CGPA Report")

    # Title
    pdf.setFont("Helvetica-Bold", 22)

    pdf.drawCentredString(
        300,
        780,
        "CGPA CALCULATOR REPORT"
    )

    # Student details
    pdf.setFont("Helvetica", 12)

    pdf.drawString(
        70,
        735,
        f"Student Name : {student_name}"
    )

    pdf.drawString(
        70,
        710,
        f"Register No  : {reg_no}"
    )

    # Table
    table_data = [
        ["Semester", "GPA", "Credits"]
    ]

    for semester, data in semester_data.items():

        table_data.append([
            semester,
            str(data["gpa"]),
            str(data["credits"])
        ])

    table = Table(
        table_data,
        colWidths=[180, 120, 120],
        rowHeights=30
    )

    table.setStyle(
        TableStyle([

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),

            ("FONTSIZE", (0, 0), (-1, -1), 11),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

            ("TOPPADDING", (0, 0), (-1, -1), 8),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    table_width, table_height = table.wrap(
        500,
        400
    )

    table.drawOn(
        pdf,
        60,
        650 - table_height
    )

    # Overall CGPA
    pdf.setFont(
        "Helvetica-Bold",
        16
    )

    pdf.drawString(
        70,
        650 - table_height - 45,
        f"Overall CGPA : {cgpa}"
    )

    # Footer
    pdf.setFont(
        "Helvetica",
        10
    )

    pdf.drawCentredString(
        300,
        50,
        "Generated by CGPA Calculator"
    )

    pdf.save()

    pdf_buffer.seek(0)

    return send_file(
        pdf_buffer,
        as_attachment=True,
        download_name="CGPA_Report.pdf",
        mimetype="application/pdf"
    )

# =========================
# SAVE CGPA
# =========================

@app.route("/download-gpa-pdf")
def download_gpa_pdf():

    student_name = session.get("student_name", "Student")
    reg_no = session.get("reg_no", "N/A")

    gpa_report = session.get("gpa_report", {})

    semester = gpa_report.get("semester", "N/A")
    subjects = gpa_report.get("subjects", [])
    gpa = gpa_report.get("gpa", "N/A")

    pdf_buffer = BytesIO()

    pdf = canvas.Canvas(pdf_buffer)
    pdf.setTitle("GPA Report")

    # =========================
    # TITLE
    # =========================

    pdf.setFont("Helvetica-Bold", 22)

    pdf.drawCentredString(
        300,
        780,
        "GPA CALCULATOR REPORT"
    )

    # =========================
    # STUDENT DETAILS
    # =========================

    pdf.setFont("Helvetica", 12)

    pdf.drawString(
        70,
        735,
        f"Student Name : {student_name}"
    )

    pdf.drawString(
        70,
        710,
        f"Register No  : {reg_no}"
    )

    pdf.drawString(
        70,
        685,
        f"Semester     : Semester {semester}"
    )

    # =========================
    # TABLE
    # =========================

    table_data = [
        ["Subject", "Credits", "Grade"]
    ]

    for subject in subjects:

        table_data.append([
            subject["name"],
            str(subject["credits"]),
            subject["grade"]
        ])

    table = Table(
        table_data,
        colWidths=[240, 100, 100],
        rowHeights=32
    )

    table.setStyle(
        TableStyle([

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),

            ("FONTSIZE", (0, 0), (-1, -1), 11),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

            ("TOPPADDING", (0, 0), (-1, -1), 8),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    # =========================
    # TABLE POSITION
    # =========================

    table_width, table_height = table.wrap(
        500,
        400
    )

    table_x = 60
    table_y = 620 - table_height

    table.drawOn(
        pdf,
        table_x,
        table_y
    )

    # =========================
    # GPA RESULT
    # =========================

    pdf.setFont(
        "Helvetica-Bold",
        16
    )

    pdf.drawString(
        70,
        table_y - 45,
        f"Semester GPA : {gpa}"
    )

    # =========================
    # FOOTER
    # =========================

    pdf.setFont(
        "Helvetica",
        10
    )

    pdf.drawCentredString(
        300,
        50,
        "Generated by GPA Calculator"
    )

    # =========================
    # SAVE PDF
    # =========================

    pdf.save()

    pdf_buffer.seek(0)

    return send_file(
        pdf_buffer,
        as_attachment=True,
        download_name=f"Semester_{semester}_GPA_Report.pdf",
        mimetype="application/pdf"
    )
# =========================
# RUN APPLICATION
# =========================

if __name__ == "__main__":
    app.run(debug=True)